# Generated by Django 5.1.6 on 2025-10-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('member', 'Membro'), ('librarian', 'Bibliotecário'), ('admin', 'Administrador')], default='member', max_length=20),
        ),
    ]
